#!/bin/bash
set -euo pipefail

# Regenerate the vendored pure-Python Snowball stemmers in
# src/scolta/index/snowball/.
#
# The stemmers are generated by the Snowball compiler's `-python` backend at
# the pinned commit below and vendored verbatim — no source transforms are
# needed (unlike the PHP port, the Python backend already emits PSR-clean,
# floor-compatible code). Output must stay byte-identical to the sha256
# manifest in src/scolta/index/snowball/PROVENANCE.md; the stemmer provenance
# test fails until the manifest is re-baselined, so regeneration is always
# explicit.
#
# WARNING — the pin is a mainline COMMIT, not a release tag, and that is
# deliberate: it is the exact snowball revision pagefind_stem 1.0.0 (the crate
# inside Pagefind 1.5.0's query WASM) was generated from, verified by
# byte-comparing the compiler output against the crate's vendored sources.
# Neither adjacent tag is parity-correct, and — critically — NO published
# `snowballstemmer` PyPI release reproduces it either:
#   - v3.0.0 / 3.0.1 diverge on 18 English words (internal, interval,
#     interfered, skis, ...) — they predate the english.sbl fixes the crate
#     has.
#   - v3.1.0 / 3.1.1 diverge on da/fi/it/no (and de apostrophe words): snowball
#     3.1.x added apostrophe/elision handling Pagefind 1.5.0 does not have
#     (2,103 divergent words across the committed corpora).
# Both were measured against this package's 14-language corpus. That is why we
# vendor the compiler output at this commit instead of depending on the
# `snowballstemmer` package.
#
# Also: the "Generated from X.sbl by Snowball <version>" header in each file is
# the compiler's own version string, not proof of the algorithm state — this
# commit self-reports "3.0.0". Trust the commit hash, never the header.
#
# Usage: ./scripts/generate-stemmers.sh
# Requires a C compiler + make (to build the Snowball compiler). Run manually,
# commit the output. Not run during CI.

SNOWBALL_REPO="https://github.com/snowballstem/snowball.git"
# Mainline commit between v3.0.0 and v3.1.0: "Support -eprefix for all target
# languages". See WARNING above for why this exact revision.
SNOWBALL_COMMIT="019c1bdd5fa3925257f30b225a2c4eba49968fe8"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
OUT_DIR="${PACKAGE_DIR}/src/scolta/index/snowball"

# Language code => Snowball algorithm name. This is exactly the set Pagefind
# 1.5.0 enables for these codes (pagefind_web/Cargo.toml feature map): note
# nl => dutch is the MODERN dutch algorithm, not dutch_porter.
ALGORITHMS=(
    catalan danish german english spanish finnish french
    italian dutch norwegian portuguese romanian russian swedish
)

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "Cloning snowball at ${SNOWBALL_COMMIT}..."
git clone --quiet "${SNOWBALL_REPO}" "${WORK_DIR}/snowball"
git -C "${WORK_DIR}/snowball" checkout --quiet "${SNOWBALL_COMMIT}"

ACTUAL_COMMIT="$(git -C "${WORK_DIR}/snowball" rev-parse HEAD)"
if [ "${ACTUAL_COMMIT}" != "${SNOWBALL_COMMIT}" ]; then
    echo "ERROR: checkout resolved to ${ACTUAL_COMMIT}, expected ${SNOWBALL_COMMIT}." >&2
    exit 1
fi

echo "Building the Snowball compiler..."
make -s -C "${WORK_DIR}/snowball" snowball >/dev/null

mkdir -p "${OUT_DIR}"
rm -f "${OUT_DIR}"/*.py "${OUT_DIR}/LICENSE"

echo "Vendoring the runtime (base stemmer + Among)..."
cp "${WORK_DIR}/snowball/python/snowballstemmer/basestemmer.py" "${OUT_DIR}/basestemmer.py"
cp "${WORK_DIR}/snowball/python/snowballstemmer/among.py" "${OUT_DIR}/among.py"

for algorithm in "${ALGORITHMS[@]}"; do
    echo "Generating ${algorithm}_stemmer.py..."
    # The same flags the snowball GNUmakefile uses for its own Python package
    # build: -python backend, -eprefix _ (the stem entry point becomes _stem()).
    "${WORK_DIR}/snowball/snowball" \
        "${WORK_DIR}/snowball/algorithms/${algorithm}.sbl" \
        -python -eprefix _ \
        -o "${OUT_DIR}/${algorithm}_stemmer.py"
done

echo "Writing the package marker..."
cat > "${OUT_DIR}/__init__.py" <<'PYEOF'
"""Vendored pure-Python Snowball stemmers — generated code, do not edit.

Produced by the Snowball compiler's ``-python`` backend at the commit pinned in
PROVENANCE.md (the revision Pagefind 1.5.0's ``pagefind_stem`` 1.0.0 query WASM
was generated from). Regenerate with ``scripts/generate-stemmers.sh``; the
stemmer provenance test pins every file to the sha256 manifest in PROVENANCE.md.

``scolta.index.stemmer.Stemmer`` maps language codes onto the ``<Algo>Stemmer``
classes here and calls their ``stemWord`` method.
"""
PYEOF

echo "Copying the Snowball license..."
cp "${WORK_DIR}/snowball/COPYING" "${OUT_DIR}/LICENSE"

# Guard: the floor is Python 3.10. The -python backend targets old Pythons, so
# this should never fire, but fail closed if a future revision emits newer
# syntax (match statements, the walrus operator is fine on 3.10).
echo "Checking for post-3.10 syntax in the output..."
if grep -nE '^\s*match .*:\s*$|^\s*case .*:\s*$' "${OUT_DIR}"/*.py; then
    echo "ERROR: match/case (3.10+ in a way the floor may not want) found; review." >&2
    exit 1
fi

echo
echo "sha256 manifest (update PROVENANCE.md if these changed):"
(cd "${OUT_DIR}" && shasum -a 256 ./*.py LICENSE | sed 's|\./||')
echo
echo "Done. Generated from snowball commit ${ACTUAL_COMMIT}."
echo "Now run the parity tests: uv run pytest tests/index/test_stemmer.py tests/index/test_stemmer_provenance.py -q"
